name: Load all vocabs Test
on:
  workflow_dispatch:
jobs:
  load_all_vocabs:
    runs-on: ubuntu-latest
    steps:
      - name: Bring in repo - test branch
        uses: actions/checkout@v1
        with:
          ref: test
      - name: Install Python dependencies
        run: |
          python -m pip install -U pip
          pip install -r scripts/requirements.txt
      - name: Load all vocabs Test
        env:
          DB_USERNAME: ${{secrets.DB_USERNAME_TEST}}
          DB_PASSWORD: ${{secrets.DB_PASSWORD_TEST}}
          BASE_DB_URI: ${{vars.BASE_DB_URI_TEST}}
        run: |
          echo 'Run load script...'
          python scripts/load_all_vocabs.py