name: Handle updated vocabs Test
on:
  push:
    branches: [ test ]

  workflow_dispatch:
jobs:
  changes:
    runs-on: ubuntu-latest
    steps:
      - name: Bring in repo - test branch
        uses: actions/checkout@v1
        with:
          ref: test
      - name: install Python dependencies
        run: |
          python -m pip install -U pip
          pip install -r scripts/requirements.txt
      - id: file_changes
        uses: trilom/file-changes-action@v1.2.4
        with:
          output: ','
      - name: detect file changes
        env:
            DB_USERNAME: ${{secrets.DB_USERNAME_TEST}}
            DB_PASSWORD: ${{secrets.DB_PASSWORD_TEST}}
            BASE_DB_URI: ${{vars.BASE_DB_URI_TEST}}
            WEBSITE_URL: ${{vars.WEBSITE_URL_TEST}}
        run: |
          echo 'Run update script...'
          a=${{steps.file_changes.outputs.files_added}}
          m=${{steps.file_changes.outputs.files_modified}}
          d=${{steps.file_changes.outputs.files_removed}}
          r=${{steps.file_changes.outputs.files_renamed}}
          if [ -z $a ]; then a="x"; fi
          if [ -z $m ]; then m="x"; fi
          if [ -z $d ]; then d="x"; fi
          if [ -z $r ]; then r="x"; fi
          python scripts/update_vocabs.py -a $a -m $m -d $d -r $r
