name: Validate Vocabs Test
on:
  pull_request:
    branches: [ test ]

  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Bring in repo - test branch
        uses: actions/checkout@v1
        with:
          ref: test
      - name: install Python dependencies
        run: |
          python -m pip install -U pip
          pip install -r scripts/requirements.txt
      - name: Validate all vocabs
        run: |
          python scripts/validate_vocabs.py
